# Naming conventions:
#
# fl - front left  | fr - front right
# cl - center left | cr - center right
# rl - rear left   | rr - rear right

# Pin numbers for motors on PWM board
pin_drive_fl: 15
pin_steer_fl: 13

pin_drive_fr: 8
pin_steer_fr: 11

pin_drive_cl: 14
pin_steer_cl: 12

pin_drive_cr: 9
pin_steer_cr: 10

pin_drive_rl: 7
pin_steer_rl: 5

pin_drive_rr: 6
pin_steer_rr: 4

## PWM values
# Those values highly depend on the motors and pwm board used
# Check out the wiki for further explanation

# PWM values for the neutral steering position
steer_pwm_neutral_fl: 340
steer_pwm_neutral_fr: 340
steer_pwm_neutral_cl: 335
steer_pwm_neutral_cr: 350
steer_pwm_neutral_rl: 315
steer_pwm_neutral_rr: 315

# PWW range around steering neutral position
steer_pwm_range_fl: 190
steer_pwm_range_fr: 190
steer_pwm_range_cl: 192
steer_pwm_range_cr: 190
steer_pwm_range_rl: 190
steer_pwm_range_rr: 192

# PWM value for the stop position of driving motors
drive_pwm_neutral: 307

# PWW range around driving neutral position
drive_pwm_range: 41

# Select connected controller (possible options: "logitech-F710" or "xbox-one")
controller: "logitech-F710"